services:
  - type: web
    name: jate-server
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    regions:
      - oregon